services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: meineapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
